
services:
  osm-pbf-to-csv:
    build: ./osm-pbf-to-csv
    volumes:
      - ./data:/input
      - /tmp:/tmp  # Share the host's /tmp

  osm-minutely-changes:
    build: ./osm-minutely-changes
    volumes:
      - ./data:/data
      - ./output:/output
      - /tmp:/tmp  # Share the host's /tmp
