services:
  osm-minutely-changes:
    build:
      context: osm-minutely-changes/
    restart: no
    # Ensure all output goes to docker logs
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - VERBOSE
      - NODES
      - WAYS
      - RELATIONS
      - TAGS
  osm-pbf-to-csv:
    build:
      context: osm-pbf-to-csv/
    restart: no
    tty: true
    stdin_open: true
    volumes:
      - ./data:/input
      - ./output:/output
    
  etag-checker:
    build:
      context: ./etag-checker
    restart: no
    environment:
      - ODF_ETAG
      - ODF_NEW_ETAG_PATH
    volumes:
      - ./data:/input
      - ./output:/output
    depends_on:
      - osm-pbf-to-csv